import "@/app/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NextUIProvider } from "@nextui-org/react";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Footer from "@/components/footer/Footer";
import TopMenu from "@/components/header/topbar/TopMenu";
import NavigateMenu from "@/components/navigate/NavigateMenu";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import FloatingWrapper from "@/components/floating/FloatingWrapper";
import "swiper/css";
import "swiper/css/pagination";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <ToastContainer />
          <FloatingWrapper />
          <TopMenu locale={locale} />
          <NavigateMenu />
          <NextUIProvider locale={locale}>{children}</NextUIProvider>
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
